# PostgreSQL Docker setup

services:
  postgres:
    image: postgres:15-alpine
    container_name: svelte-starter-postgres
    environment:
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      POSTGRES_DB: ${DB_NAME:?err}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}', '-d', '${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - '127.0.0.1:${DB_PORT:-5432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
